# 파이썬 과제 지시서
## 과제명 “서울 지하철 데이터로 나만의 지도 만들기” — OpenAPI 연동 실습

 <작업 예정 순서>
1. 서울 열린 데이터 광장 OPEN API 활용 | 서울교통공사_역주소 및 전화번호 데이터 가져오기
2. 국토교통부 V WORLD OPEN API 활용 | 주소를 좌표로 변환해보기
3. pandas의 조인 문법 활용, 주소를 기준으로 하나의 데이터 프레임 형태로 만들기

### [1] 서울 열린 데이터 광장 OPEN API 활용 | 서울교통공사_역주소 및 전화번호 데이터 가져오기

- STEP 1. 라이브러리 참조하기
- STEP 2. 요청 정보 확인
- STEP 3. 웹 데이터 요청하기
- STEP 4. 지하철역 주소 데이터 응답 결과 구조 확인

###

### STEP 1. 라이브러리 참조하기

In [2]:
import requests
from pandas import DataFrame
import json

### STEP 2. 요청 정보 확인

In [3]:
#인증키
KEY = "6b6c4e4849626f683933564c44446a"
# 필수 파라미터
TYPE='json'
SERVICE= "StationAdresTelno"
START_INDEX = 1
END_INDEX=1000


#요청 URL path 형식
base_url = "http://openapi.seoul.go.kr:8088"
path = f"/{KEY}/{TYPE}/{SERVICE}/{START_INDEX}/{END_INDEX}/"
url = base_url+path

print(url)

http://openapi.seoul.go.kr:8088/6b6c4e4849626f683933564c44446a/json/StationAdresTelno/1/1000/

### 3. 웹 데이터 요청하기

In [4]:
with requests.Session() as session:

  #세션 객체에 웹 브라우저 정보 (UserAgent) 주입 (웹서버가 파이썬 프로그램을 정상적인 웹 브라우저로 여기도록)
  session.headers.update({"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
                          })
  

  r=session.get(url)    
  print(r.url)

  if r.status_code !=200:
    msg ="[%d Error] %s 에러가 발생함" % (r.status_code,r.reason)
    raise Exception(msg)

print(r) # HTTP 통신 상태 확인

r.encoding ="utf-8"
mydict = r.json()
resultset = mydict["StationAdresTelno"]["row"]
print(mydict["StationAdresTelno"]["row"])

http://openapi.seoul.go.kr:8088/6b6c4e4849626f683933564c44446a/json/StationAdresTelno/1/1000/
<Response [200]>

### 4. 지하철역 주소 데이터 응답 결과 구조 확인

In [5]:
metro_df = DataFrame(resultset)
metro_df

,SBWY_ROUT_LN,SBWY_STNS_NM,OLD_ADDR,ROAD_NM_ADDR,TELNO
0,1호선,서울,서울특별시 중구 남대문로5가 73-6 서울역(1호선),서울특별시 중구 세종대로 지하2(남대문로 5가),02-6110-1331
1,1호선,시청,서울특별시 중구 정동 5-5 시청역(1호선),서울특별시 중구 세종대로 지하101(정동),02-6110-1321
2,1호선,종각,서울특별시 종로구 종로1가 54 종각역(1호선),서울특별시 종로구 종로 지하55(종로1가),02-6110-1311
3,1호선,종로3가,서울특별시 종로구 종로3가 10-5 종로3가역(1호선),서울특별시 종로구 종로 지하129(종로3가),02-6110-1301
4,1호선,종로5가,서울특별시 종로구 종로5가 82-1 종로5가역(1호선),서울특별시 종로구 종로 지하216(종로5가),02-6110-1291
...,...,...,...,...,...
284,9호선,송파나루,서울특별시 송파구 방이동 2 송파나루역(9호선),서울특별시 송파구 백제고분로 지하446(방이동),02-2656-0934
285,9호선,한성백제,서울특별시 송파구 방이동 88-17 한성백제역(9호선),서울특별시 송파구 위례성대로 지하29(방이동),02-2656-0935
286,9호선,올림픽공원(한국체대),서울특별시 송파구 방이동 89-28 올림픽공원역(9호선),서울특별시 송파구 양재대로 지하1233(방이동),02-2656-0936
287,9호선,둔촌오륜,서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선),서울특별시 강동구 강동대로 지하303(둔촌동),02-2656-0937
288,9호선,중앙보훈병원,서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선),서울특별시 강동구 동남로 지하625(둔촌동),02-2656-0938

In [6]:
#type =parcel 에 해당하는 주소인 OLD_ADDR 활용, 해당 주소 리스트를 국토교통부 API에 활용하여 주소를 좌표로 변환할 예정
OLD_ADDR_list =[]

for v,item in enumerate(resultset):

  OLD_ADDR_list.append(item["OLD_ADDR"])

print(OLD_ADDR_list)

['서울특별시 중구 남대문로5가 73-6 서울역(1호선)', '서울특별시 중구 정동 5-5 시청역(1호선)', '서울특별시 종로구 종로1가 54 종각역(1호선)', '서울특별시 종로구 종로3가 10-5 종로3가역(1호선)', '서울특별시 종로구 종로5가 82-1 종로5가역(1호선)', '서울특별시 종로구 창신동 492-1 동대문역(1호선)', '서울특별시 동대문구 신설동 76-5 신설동역(1호선)', '서울특별시 동대문구 제기동 65 제기동역(1호선)', '서울특별시 동대문구 전농동 620-69 청량리역(1호선)', '서울특별시 종로구 숭인동 117 동묘앞역(1호선)', '서울특별시 중구 서소문동 90-1 시청역(2호선)', '서울특별시 중구 을지로1가 100-1 을지로입구역(2호선)', '서울특별시 중구 을지로3가 347-3 을지로3가역(2호선)', '서울특별시 중구 을지로4가 267-1 을지로4가역(2호선)', '서울특별시 중구 을지로 7가 112-3 동대문역사문화공원역(2호선)', '서울특별시 중구 신당동 99 신당역(2호선)', '서울특별시 성동구 하왕십리동 946-14 상왕십리역(2호선)', '서울특별시 성동구 행당동 192 왕십리역(2호선)', '서울특별시 성동구 행당동 산17 한양대역(2호선)', '서울특별시 성동구 성수동1가 656-745 뚝섬역(2호선)', '서울특별시 성동구 성수동2가 300-1 성수역(2호선)', '서울특별시 광진구 화양동 7-3 2호선 건대입구역(2호선)', '서울특별시 광진구 구의동 245-24 구의역(2호선)', '서울특별시 광진구 구의동 546-6 강변역(2호선)', '서울특별시 송파구 신천동 15 잠실나루역(2호선)', '서울특별시 송파구 신천동 8 잠실역(2호선)', '서울특별시 송파구 잠실동 33 잠실새내역(2호선)', '서울특별시 송파구 잠실동 122 종합운동장역(2호선)', '서울특별시 강남구 삼성동 172-66 삼성역(2호선)', '서울특별시 강남구 삼성동 172-66 선릉역(2호선)', '서울특별시 강남구 역삼동 804 역삼역(2호선)', '서울특별시 강남구 역삼동 858 강남역(2호선)', '서울특별시 서초구 서초동 1748-4 교대역(2호선)', '서울특별시 서초구 서초동 1748-5 서초역(2호선)', '서울특별시 서초구 방배동 912-14 방배역(2호선)', '서울특별시 동작구 사당동 1129 사당역(2호선)', '서울특별시 관악구 봉천동 1693-39 낙성대역(2호선)', '서울특별시 관악구 봉천동 979-2 서울대입구역(2호선)', '서울툭별시 관악구 봉천동 979-7 봉천역(2호선)', '서울특별시 관악구 신림동 1467-10 신림역(2호선)', '서울특별시 동작구 신대방동 643-1 신대방역(2호선)', '서울특별시 구로구 구로동 810-3 구로디지털단지역(2호선)', '서울특별시 구로구 구로동 1204 대림역(2호선)', '서울특별시 구로구 신도림동 460-26 신도림역(2호선)', '서울특별시 영등포구 문래동3가 68-1 문래역(2호선)', '서울특별시 영등포구 당산동3가 270-1 영등포구청역(2호선)', '서울특별시 영등포구 당산동 6가 323-1 당산역(2호선)', '서울특별시 마포구 서교동 393 합정역(2호선)', '서울특별시 마포구 동교동 165 홍대입구역(2호선)', '서울특별시 마포구 노고산동 31-11 신촌역(2호선)', '서울특별시 마포구 염리동 8-85 이대역(2호선)', '서울특별시 마포구 아현동 354-23 아현역(2호선)', '서울특별시 서대문구 충정로3가 319-1 충정로역(2호선)', '서울특별시 성동구 용답동 127 용답역(2호선)', '서울특별시 성동구 용답동 129-2 신답역(2호선)', '서울특별시 동대문구 신설동 76-5 신설동역(2호선)', '서울특별시 구로구 신도림동 323-16 도림천역(2호선)', '서울특별시 양천구 신정동 276-7 양천구청역(2호선)', '서울특별시 양천구 신정동 1231 신정네거리역(2호선)', '서울특별시 동대문구 용두동 47-1 용두역(2호선)', '경기도 고양시 덕양구 지축동 818-64 지축역(3호선)', '서울특별시 은평구 진관동 67-26 구파발역(3호선)', '서울특별시 은평구 갈현동 397 연신내역(3호선)', '서울특별시 은평구 대조동 13-10 불광역(3호선)', '서울특별시 은평구 녹번동 55 녹번역(3호선)', '서울특별시 서대문구 홍제동 161-1 홍제역(3호선)', '서울특별시 서대문구 홍제동 26-1 무악재역(3호선)', '서울특별시 서대문구 현저동 101 독립문역(3호선)', '서울특별시 종로구 적선동 81-1 경복궁역(3호선)', '서울특별시 종로구 안국동 73-1 안국역(3호선)', '서울특별시 종로구 묘동 20-5 종로3가역(3호선)', '서울특별시 중구 을지로3가 282-8 을지로3가역(3호선)', '서울특별시 중구 필동2가 16-2 충무로역(3호선)', '서울특별시 중구 장충동2가 199-3 동대입구역(3호선)', '서울특별시 중구 신당동 369-44 약수역(3호선)', '서울특별시 성동구 금호동4가 1470 금호역(3호선)', '서울특별시 성동구 옥수동 168-1 옥수역(3호선)', '서울특별시 강남구 신사동 668 압구정역(3호선)', '서울특별시 강남구 신사동 667 신사역(3호선)', '서울특별시 서초구 잠원동 100-1 잠원역(3호선)', '서울특별시 서초구 반포동 19-11 고속터미널역(3호선)', '서울특별시 서초구 서초동 1748-4 교대역(3호선)', '서울특별시 서초구 서초동 1748-30 남부터미널역(3호선)', '서울특별시 서초구 서초동 1366-9 양재역(3호선)', '서울특별시 강남구 도곡동 179-2 매봉역(3호선)', '서울특별시 강남구 도곡동 339-2 도곡역(3호선)', '서울특별시 강남구 대치동 317-3 대치역(3호선)', '서울특별시 강남구 대치동 514-3 학여울역(3호선)', '서울특별시 강남구 일원동 700-9 대청역(3호선)', '서울특별시 강남구 일원동 717 일원역(3호선)', '서울특별시 강남구 수서동 728 수서역(3호선)', '서울특별시 송파구 가락동 184-23 가락시장역(3호선)', '서울특별시 송파구 가락동 10-15 경찰병원역(3호선)', '서울특별시 송파구 오금동 44-2 오금역(3호선)', '서울특별시 노원구 상계동 111 당고개역(4호선)', '서울특별시 노원구 상계동 156-203 상계역(4호선)', '서울특별시 노원구 상계동 602-5 노원역(4호선)', '서울특별시 도봉구 창동 135-1 창동역(4호선)', '서울특별시 도봉구 창동 703-4 쌍문역(4호선)', '서울특별시 강북구 수유동 140 수유역(4호선)', '서울특별시 강북구 미아동 194-1 미아역(4호선)', '서울특별시 강북구 미아동 66-1 미아사거리역(4호선)', '서울특별시 성북구 길음동 877-66 길음역(4호선)', '서울특별시 성북구 동선동4가 1 성신여대입구역(4호선)', '서울특별시 성북구 삼선동1가 14 한성대입구역(4호선)', '서울특별시 종로구 명륜4가 96-5 혜화역(4호선)', '서울특별시 종로구 종로6가 287-1 동대문역(4호선)', '서울특별시 중구 광희동2가 9 동대문역사문화공원역(4호선)', '서울특별시 중구 필동2가 16-2 충무로역(4호선)', '서울특별시 중구 충무로2가 109-2 명동역(4호선)', '서울특별시 중구 남창동 64-1 회현역(4호선)', '서울특별시 용산구 동자동 14-151 서울역 (4호선)', '서울특별시 용산구 갈월동 16-7 숙대입구역(4호선)', '서울특별시 용산구 한강로1가 228-1 삼각지역(4호선)', '서울특별시 용산구 한강로2가 181 신용산역(4호선)', '서울특별시 용산구 용산동5가 17-112 이촌역(4호선)', '서울특별시 동작구 동작동 327-1 동작역(4호선)', '서울특별시 동작구 사당동 736-1 총신대입구(이수)역(4호선)', '서울특별시 동작구 사당동 588-44 사당역(4호선)', '서울특별시 서초구 방배동 2909 남태령역(4호선)', '서울특별시 강서구 방화동 829-15 방화역(5호선)', '서울특별시 강서구 방화동 846 개화산역(5호선)', '서울특별시 강서구 방화동 886 김포공항역(5호선)', '서울특별시 강서구 공항동 29-5 송정역(5호선)', '서울특별시 강서구 마곡동 769-3 마곡역(5호선)', '서울특별시 강서구 마곡동 727-1496 발산역(5호선)', '서울특별시 강서구 화곡동 1089-3 우장산역(5호선)', '서울특별시 강서구 화곡동 1089-54 화곡역(5호선)', '서울특별시 강서구 화곡동 662-5 까치산역(5호선)', '서울특별시 양천구 신정동 1090 신정역(5호선)', '서울특별시 양천구 목동 926-3 목동역(5호선)', '서울특별시 양천구 목동 406-30 오목교역(5호선)', '서울특별시 영등포구 양평동2가 33-79 양평역(5호선)', '서울특별시 영등포구 당산동3가 556-1 영등포구청역(5호선)', '서울특별시 영등포구 영등포동5가 62-1 영등포시장역(5호선)', '서울특별시 영등포구 영등포동1가 35 신길역(5호선)', '서울특별시 영등포구 여의도동 3 여의도역(5호선)', '서울특별시 영등포구 여의도동 84-4 여의나루역(5호선)', '서울특별시 마포구 도화동 160 마포역(5호선)', '서울특별시 마포구 공덕동 423-29 공덕역(5호선)', '서울특별시 마포구 아현동 612 애오개역(5호선)', '서울특별시 서대문구 충정로3가 248-1 충정로역(5호선)', '서울특별시 종로구 평동 210 서대문역(5호선)', '서울특별시 종로구 세종로 1-68 5호선 광화문역(5호선)', '서울특별시 종로구 돈의동 39-1 5호선 종로3가역(5호선)', '서울특별시 중구 주교동 191 을지로4가역(5호선)', '서울특별시 중구 광희동1가 235-6 동대문역사문화공원역(5호선)', '서울특별시 중구 신당동 295-2 청구역(5호선)', '서울특별시 성동구 금호동2가 223-1 신금호역(5호선)', '서울특별시 성동구 행당동 317-241 행당역(5호선)', '서울특별시 성동구 행당동 192 왕십리역(5호선)', '서울특별시 성동구 마장동 804 마장역(5호선)', '서울특별시 성동구 용답동 99 답십리역(5호선)', '서울특별시 동대문구 장안동 472-3 장한평역(5호선)', '서울특별시 광진구 능동 275-5 군자(능동)역(5호선)', '서울특별시 광진구 능동 256-16 5호선 아차산역(5호선)', '서울특별시 광진구 광장동 237 광나루역(5호선)', '서울특별시 강동구 천호동 455 천호역(5호선)', '서울특별시 강동구 천호동 447 강동역(5호선)', '서울특별시 강동구 길동 378 길동역(5호선)', '서울특별시 강동구 명일동 345-12 굽은다리역(5호선)', '서울특별시 강동구 명일동 312 명일역(5호선)', '서울특별시 강동구 고덕동 310 고덕역(5호선)', '서울특별시 강동구 상일동 148 상일동역(5호선)', '서울특별시 강동구 둔촌동 416 둔촌동역(5호선)', '서울특별시 송파구 방이동 89-28 올림픽공원역(5호선)', '서울특별시 송파구 방이동 217-2 방이역(5호선)', '서울특별시 송파구 오금동 44-2 오금역(5호선)', '서울특별시 송파구 가락동 165-2 개롱역(5호선)', '서울특별시 송파구 거여동 20-14 거여역(5호선)', '서울특별시 송파구 마천동 307-4 마천역(5호선)', '서울특별시 강동구 상일동 산73 강일역(5호선)', '경기도 하남시 망월동 1122 미사역(5호선)', '경기도 하남시 덕풍동 727-3 하남풍산역(5호선)', '경기도 하남시 덕풍동 405-1 하남시청(덕풍신장)역(5호선)', '경기도 하남시 창우동 526 하남검단산역(5호선)', '서울특별시 은평구 신사동 22-15 응암역(6호선)', '서울특별시 은평구 녹번동 153-31 역촌역(6호선)', '서울특별시 은평구 대조동 13-10 불광역(6호선)', '서울특별시 은평구 불광동 13-33 독바위역(6호선)', '서울특별시 은평구 갈현동 397 연신내역(6호선)', '서울특별시 은평구 구산동 1 구산역(6호선)', '서울특별시 은평구 신사동 337-5 새절역(6호선)', '서울특별시 은평구 증산동 199-8 증산역(6호선)', '서울특별시 은평구 증산동 223-25 디지털미디어시티역(6호선)', '서울특별시 마포구 성산동 420 월드컵경기장역(6호선)', '서울특별시 마포구 성산동 592 마포구청역(6호선)', '서울특별시 마포구 망원동 378 망원역(6호선)', '서울특별시 마포구 합정동 414 합정역(6호선)', '서울특별시 마포구 상수동 309-10 상수역(6호선)', '서울특별시 마포구 창전동 145-17 광흥창역(6호선)', '서울특별시 마포구 대흥동 128-1 대흥역(6호선)', '서울특별시 마포구 공덕동 439 공덕역(6호선)', '서울특별시 용산구 효창동 80 효창공원앞역(6호선)', '서울특별시 용산구 한강로1가 228-1 삼각지역(6호선)', '서울특별시 용산구 용산동4가 4 녹사평역(6호선)', '서울특별시 용산구 이태원동 119-23 이태원역(6호선)', '서울특별시 용산구 한남동 726-494 한강진역(6호선)', '서울특별시 중구 신당동 366-454 버티고개역(6호선)', '서울특별시 중구 신당동 369-2 약수역(6호선)', '서울특별시 중구 신당동 295-2 청구역(6호선)', '서울특별시 중구 흥인동 162-1 신당역(6호선)', '서울특별시 종로구 숭인동 316-3 동묘앞역(6호선)', '서울특별시 종로구 창신동 20-8 창신역(6호선)', '서울특별시 성북구 보문동1가 127-1 보문역(6호선)', '서울특별시 성북구 안암동5가 146-1 안암역(6호선)', '서울특별시 성북구 종암동 29-18 고려대역(6호선)', '서울특별시 성북구 하월곡동 35-1 월곡역(6호선)', '서울특별시 성북구 상월곡동 26-1 상월곡역(6호선)', '서울특별시 성북구 석관동 349-8 돌곶이역(6호선)', '서울특별시 노원구 월계동 25-2 석계역(6호선)', '서울특별시 노원구 공릉동 616-4 태릉입구역(6호선)', '서울특별시 노원구 공릉동 285-2 화랑대역(6호선)', '서울특별시 중랑구 신내동 643-1 봉화산역(6호선)', '서울특별시 중랑구 신내동 19 신내역(6호선)', '경기도 의정부시 장암동 160-8 장암역(7호선)', '서울특별시 도봉구 도봉동 38-3 도봉산역(7호선)', '서울특별시 노원구 상계동 1132-9 수락산역(7호선)', '서울특별시 노원구 상계동 650 마들역(7호선)', '서울특별시 노원구 상계동 729 노원역(7호선)', '서울특별시 노원구 중계동 503-3 중계역(7호선)', '서울특별시 노원구 하계동 273-5 하계역(7호선)', '서울특별시 노원구 공릉동 385-4 공릉역(7호선)', '서울특별시 노원구 공릉동 616-4 태릉입구역(7호선)', '서울특별시 중랑구 묵동 189-5 먹골역(7호선)', '서울특별시 중랑구 중화동 50-3 중화역(7호선)', '서울특별시 중랑구 상봉동 100-9 상봉역(7호선)', '서울특별시 중랑구 면목동 282-6 면목역(7호선)', '서울특별시 중랑구 면목동 495 사가정역(7호선)', '서울특별시 중랑구 면목동 1316-5 용마산역(7호선)', '서울특별시 광진구 중곡동 273-2 7호선 중곡역(7호선)', '서울특별시 광진구 능동 275-5 군자(능동)역(7호선)', '서울특별시 광진구 화양동 164-1 어린이대공원역(7호선)', '서울특별시 광진구 화양동 6-3 건대입구역(7호선)', '서울특별시 광진구 자양동 73-2 자양(뚝섬유원지)역(7호선)', '서울특별시 강남구 청담동 77-76 청담역(7호선)', '서울특별시 강남구 삼성동 111-44 강남구청역(7호선)', '서울특별시 강남구 논현동 279-67 학동역(7호선)', '서울특별시 강남구 논현동 279-67 논현역(7호선)', '서울특별시 서초구 잠원동 103 반포역(7호선)', '서울특별시 서초구 반포동 19-11 고속터미널역(7호선)', '서울특별시 서초구 방배동 874-16 내방역(7호선)', '서울특별시 동작구 사당동 144-4 이수역(7호선)', '서울특별시 동작구 사당동 산25-33 남성역(7호선)', '서울특별시 동작구 상도동 514 숭실대입구역(7호선)', '서울특별시 동작구 상도1동 702-1 상도역(중대입구역)(7호선)', '서울특별시 동작구 상도동 26-20 장승배기역(7호선)', '서울특별시 동작구 대방동 406-10 신대방삼거리역(7호선)', '서울특별시 동작구 대방동 466-51 보라매역(7호선)', '서울특별시 영등포구 신길동 3599 신풍역(7호선)', '서울특별시 영등포구 대림동 1050-17 대림역(7호선)', '서울특별시 구로구 구로동 801-95 남구로역(7호선)', '서울특별시 금천구 가산동 468-4 가산디지털단지역(7호선)', '경기도 광명시 철산동 526 철산역(7호선)', '경기도 광명시 광명동 158-211 광명사거리역(7호선)', '서울특별시 구로구 천왕동 14-25 천왕역(7호선)', '서울특별시 구로구 온수동 119 온수역(7호선)', '서울특별시 강동구 암사동 501 암사역(8호선)', '서울특별시 강동구 암사동 378 암사역사공원역(8호선)', '서울특별시 강동구 천호동 455 천호역(8호선)', '서울특별시 강동구 성내동 319 강동구청역(8호선)', '서울특별시 송파구 신천동 19 몽촌토성역(8호선)', '서울특별시 송파구 신천동 7-4 잠실역(8호선)', '서울특별시 송파구 석촌동 209 석촌역(8호선)', '서울특별시 송파구 가락동 459-4 송파역(8호선)', '서울특별시 송파구 가락동 184-23 가락시장역(8호선)', '서울특별시 송파구 문정동 119-4 문정역(8호선)', '서울특별시 송파구 장지동 201-5 장지역(8호선)', '서울특별시 송파구 장지동 596-21 복정역(8호선)', '경기도 성남시 수정구 복정동 57 남위례역(8호선)', '경기도 성남시 수정구 신흥동 7 산성역(8호선)', '경기도 성남시 수정구 단대동 96 남한산성입구역(8호선)', '경기도 성남시 수정구 신흥동 2467 단대오거리역(8호선)', '경기도 성남시 수정구 신흥동 2467 신흥역(8호선)', '경기도 성남시 수정구 수진동 2205-1 수진역(8호선)', '경기도 성남시 수정구 수진동 4518 모란역(8호선)', '서울특별시 강남구 논현동 279-165 언주역(9호선)', '서울특별시 강남구 삼성동 111-114 선정릉역(9호선)', '서울특별시 강남구 삼성동 111-147 삼성중앙역(9호선)', '서울특별시 강남구 삼성동 172 봉은사역(9호선)', '서울특별시 송파구 잠실동 123 종합운동장역(9호선)', '서울특별시 송파구 잠실동 347 삼전역(9호선)', '서울특별시 송파구 삼전동 157-1 석촌고분역(9호선)', '서울특별시 송파구 석촌동 209 석촌역(9호선)', '서울특별시 송파구 방이동 2 송파나루역(9호선)', '서울특별시 송파구 방이동 88-17 한성백제역(9호선)', '서울특별시 송파구 방이동 89-28 올림픽공원역(9호선)', '서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선)', '서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선)']

### [2] 국토교통부 V WORLD OPEN API 활용 | 주소를 좌표로 변환해보기

- STEP 0. 라이브러리 참조하기 (생략)
- STEP 1. 요청 정보 확인
- STEP 2. 웹 데이터 요청하기
- STEP 3. 데이터 전처리
- STEP 4. 데이터 프레임 형태로 확인하기

### STEP 1. 요청 정보 확인

In [7]:
geo_url ="https://api.vworld.kr/req/address?"   #쿼리 스트링 파라미터 방식
geo_key = "1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E"
geo_list =[]

for address_info in OLD_ADDR_list:

	params = {
		"service": "address",
		"request": "getcoord",
		"crs": "epsg:4326",
		"address": address_info,
		"format": "json",
		"type": "parcel",
		"key": geo_key,
	}
	response = requests.get(geo_url, params=params)
	geo_list.append(response.url)
	
print(geo_list)

['https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EB%82%A8%EB%8C%80%EB%AC%B8%EB%A1%9C5%EA%B0%80+73-6+%EC%84%9C%EC%9A%B8%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%A0%95%EB%8F%99+5-5+%EC%8B%9C%EC%B2%AD%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A2%85%EB%A1%9C%EA%B5%AC+%EC%A2%85%EB%A1%9C1%EA%B0%80+54+%EC%A2%85%EA%B0%81%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A2%85%EB%A1%9C%EA%B5%AC+%EC%A2%85%EB%A1%9C3%EA%B0%80+10-5+%EC%A2%85%EB%A1%9C3%EA%B0%80%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A2%85%EB%A1%9C%EA%B5%AC+%EC%A2%85%EB%A1%9C5%EA%B0%80+82-1+%EC%A2%85%EB%A1%9C5%EA%B0%80%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A2%85%EB%A1%9C%EA%B5%AC+%EC%B0%BD%EC%8B%A0%EB%8F%99+492-1+%EB%8F%99%EB%8C%80%EB%AC%B8%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC+%EC%8B%A0%EC%84%A4%EB%8F%99+76-5+%EC%8B%A0%EC%84%A4%EB%8F%99%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC+%EC%A0%9C%EA%B8%B0%EB%8F%99+65+%EC%A0%9C%EA%B8%B0%EB%8F%99%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC+%EC%A0%84%EB%86%8D%EB%8F%99+620-69+%EC%B2%AD%EB%9F%89%EB%A6%AC%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A2%85%EB%A1%9C%EA%B5%AC+%EC%88%AD%EC%9D%B8%EB%8F%99+117+%EB%8F%99%EB%AC%98%EC%95%9E%EC%97%AD%281%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%84%9C%EC%86%8C%EB%AC%B8%EB%8F%99+90-1+%EC%8B%9C%EC%B2%AD%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%9D%84%EC%A7%80%EB%A1%9C1%EA%B0%80+100-1+%EC%9D%84%EC%A7%80%EB%A1%9C%EC%9E%85%EA%B5%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%9D%84%EC%A7%80%EB%A1%9C3%EA%B0%80+347-3+%EC%9D%84%EC%A7%80%EB%A1%9C3%EA%B0%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%9D%84%EC%A7%80%EB%A1%9C4%EA%B0%80+267-1+%EC%9D%84%EC%A7%80%EB%A1%9C4%EA%B0%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%9D%84%EC%A7%80%EB%A1%9C+7%EA%B0%80+112-3+%EB%8F%99%EB%8C%80%EB%AC%B8%EC%97%AD%EC%82%AC%EB%AC%B8%ED%99%94%EA%B3%B5%EC%9B%90%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%A4%91%EA%B5%AC+%EC%8B%A0%EB%8B%B9%EB%8F%99+99+%EC%8B%A0%EB%8B%B9%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%ED%95%98%EC%99%95%EC%8B%AD%EB%A6%AC%EB%8F%99+946-14+%EC%83%81%EC%99%95%EC%8B%AD%EB%A6%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%ED%96%89%EB%8B%B9%EB%8F%99+192+%EC%99%95%EC%8B%AD%EB%A6%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%ED%96%89%EB%8B%B9%EB%8F%99+%EC%82%B017+%ED%95%9C%EC%96%91%EB%8C%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%EC%84%B1%EC%88%98%EB%8F%991%EA%B0%80+656-745+%EB%9A%9D%EC%84%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%EC%84%B1%EC%88%98%EB%8F%992%EA%B0%80+300-1+%EC%84%B1%EC%88%98%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B4%91%EC%A7%84%EA%B5%AC+%ED%99%94%EC%96%91%EB%8F%99+7-3+2%ED%98%B8%EC%84%A0+%EA%B1%B4%EB%8C%80%EC%9E%85%EA%B5%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B4%91%EC%A7%84%EA%B5%AC+%EA%B5%AC%EC%9D%98%EB%8F%99+245-24+%EA%B5%AC%EC%9D%98%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B4%91%EC%A7%84%EA%B5%AC+%EA%B5%AC%EC%9D%98%EB%8F%99+546-6+%EA%B0%95%EB%B3%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%86%A1%ED%8C%8C%EA%B5%AC+%EC%8B%A0%EC%B2%9C%EB%8F%99+15+%EC%9E%A0%EC%8B%A4%EB%82%98%EB%A3%A8%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%86%A1%ED%8C%8C%EA%B5%AC+%EC%8B%A0%EC%B2%9C%EB%8F%99+8+%EC%9E%A0%EC%8B%A4%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%86%A1%ED%8C%8C%EA%B5%AC+%EC%9E%A0%EC%8B%A4%EB%8F%99+33+%EC%9E%A0%EC%8B%A4%EC%83%88%EB%82%B4%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%86%A1%ED%8C%8C%EA%B5%AC+%EC%9E%A0%EC%8B%A4%EB%8F%99+122+%EC%A2%85%ED%95%A9%EC%9A%B4%EB%8F%99%EC%9E%A5%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%82%BC%EC%84%B1%EB%8F%99+172-66+%EC%82%BC%EC%84%B1%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%82%BC%EC%84%B1%EB%8F%99+172-66+%EC%84%A0%EB%A6%89%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%97%AD%EC%82%BC%EB%8F%99+804+%EC%97%AD%EC%82%BC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%97%AD%EC%82%BC%EB%8F%99+858+%EA%B0%95%EB%82%A8%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%9C%EC%B4%88%EA%B5%AC+%EC%84%9C%EC%B4%88%EB%8F%99+1748-4+%EA%B5%90%EB%8C%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%9C%EC%B4%88%EA%B5%AC+%EC%84%9C%EC%B4%88%EB%8F%99+1748-5+%EC%84%9C%EC%B4%88%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%9C%EC%B4%88%EA%B5%AC+%EB%B0%A9%EB%B0%B0%EB%8F%99+912-14+%EB%B0%A9%EB%B0%B0%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EC%9E%91%EA%B5%AC+%EC%82%AC%EB%8B%B9%EB%8F%99+1129+%EC%82%AC%EB%8B%B9%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B4%80%EC%95%85%EA%B5%AC+%EB%B4%89%EC%B2%9C%EB%8F%99+1693-39+%EB%82%99%EC%84%B1%EB%8C%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B4%80%EC%95%85%EA%B5%AC+%EB%B4%89%EC%B2%9C%EB%8F%99+979-2+%EC%84%9C%EC%9A%B8%EB%8C%80%EC%9E%85%EA%B5%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%88%AD%EB%B3%84%EC%8B%9C+%EA%B4%80%EC%95%85%EA%B5%AC+%EB%B4%89%EC%B2%9C%EB%8F%99+979-7+%EB%B4%89%EC%B2%9C%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B4%80%EC%95%85%EA%B5%AC+%EC%8B%A0%EB%A6%BC%EB%8F%99+1467-10+%EC%8B%A0%EB%A6%BC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EC%9E%91%EA%B5%AC+%EC%8B%A0%EB%8C%80%EB%B0%A9%EB%8F%99+643-1+%EC%8B%A0%EB%8C%80%EB%B0%A9%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EA%B5%AC%EB%A1%9C%EB%8F%99+810-3+%EA%B5%AC%EB%A1%9C%EB%94%94%EC%A7%80%ED%84%B8%EB%8B%A8%EC%A7%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EA%B5%AC%EB%A1%9C%EB%8F%99+1204+%EB%8C%80%EB%A6%BC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EC%8B%A0%EB%8F%84%EB%A6%BC%EB%8F%99+460-26+%EC%8B%A0%EB%8F%84%EB%A6%BC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC+%EB%AC%B8%EB%9E%98%EB%8F%993%EA%B0%80+68-1+%EB%AC%B8%EB%9E%98%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC+%EB%8B%B9%EC%82%B0%EB%8F%993%EA%B0%80+270-1+%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC%EC%B2%AD%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%98%81%EB%93%B1%ED%8F%AC%EA%B5%AC+%EB%8B%B9%EC%82%B0%EB%8F%99+6%EA%B0%80+323-1+%EB%8B%B9%EC%82%B0%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EC%84%9C%EA%B5%90%EB%8F%99+393+%ED%95%A9%EC%A0%95%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EB%8F%99%EA%B5%90%EB%8F%99+165+%ED%99%8D%EB%8C%80%EC%9E%85%EA%B5%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EB%85%B8%EA%B3%A0%EC%82%B0%EB%8F%99+31-11+%EC%8B%A0%EC%B4%8C%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EC%97%BC%EB%A6%AC%EB%8F%99+8-85+%EC%9D%B4%EB%8C%80%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EC%95%84%ED%98%84%EB%8F%99+354-23+%EC%95%84%ED%98%84%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%9C%EB%8C%80%EB%AC%B8%EA%B5%AC+%EC%B6%A9%EC%A0%95%EB%A1%9C3%EA%B0%80+319-1+%EC%B6%A9%EC%A0%95%EB%A1%9C%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%EC%9A%A9%EB%8B%B5%EB%8F%99+127+%EC%9A%A9%EB%8B%B5%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%84%B1%EB%8F%99%EA%B5%AC+%EC%9A%A9%EB%8B%B5%EB%8F%99+129-2+%EC%8B%A0%EB%8B%B5%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC+%EC%8B%A0%EC%84%A4%EB%8F%99+76-5+%EC%8B%A0%EC%84%A4%EB%8F%99%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EC%8B%A0%EB%8F%84%EB%A6%BC%EB%8F%99+323-16+%EB%8F%84%EB%A6%BC%EC%B2%9C%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%96%91%EC%B2%9C%EA%B5%AC+%EC%8B%A0%EC%A0%95%EB%8F%99+276-7+%EC%96%91%EC%B2%9C%EA%B5%AC%EC%B2%AD%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EC%96%91%EC%B2%9C%EA%B5%AC+%EC%8B%A0%EC%A0%95%EB%8F%99+1231+%EC%8B%A0%EC%A0%95%EB%84%A4%EA%B1%B0%EB%A6%AC%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EB%8F%99%EB%8C%80%EB%AC%B8%EA%B5%AC+%EC%9A%A9%EB%91%90%EB%8F%99+47-1+%EC%9A%A9%EB%91%90%EC%97%AD%282%ED%98%B8%EC%84%A0%29&format=json&type=parcel&key=1C1C7AC9-4A35-3854-BFE7-D91FAEDD655E', 'https://api.vworld.kr/req/address?service=address&request=getcoord&crs=epsg%3A4326&address=%E

### STEP 2. 웹 데이터 요청하기

In [8]:
geo_result_dict_list =[]

with requests.Session() as session2:
  session.headers.update({"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
                          })
  

  #앞에서 준비한 주소 url 리스트를 탐색하며 접속
for e in geo_list:
  r2=session.get(e)    
  
  if r2.status_code !=200:
    msg ="[%d Error] %s 에러가 발생함" % (r2.status_code,r2.reason)
    print(msg)
    continue


  r2.encoding ="utf-8"
  geo_mydict = r2.json()
  geo_result_dict_list.append(geo_mydict)

#국토교통부 전체 데이터 확인
print(geo_result_dict_list)

[{'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 남대문로5가 73-6 서울역(1호선)'}, 'refined': {'text': '서울특별시 중구 남대문로5가 73-6', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '남대문로5가', 'level4LC': '1114011800100730006', 'level4A': '회현동', 'level4AC': '1114054000', 'level5': '73-6', 'detail': '1호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.97254323694754', 'y': '37.55702928798156'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '19(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 정동 5-5 시청역(1호선)'}, 'refined': {'text': '서울특별시 중구 정동 5-5', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '정동', 'level4LC': '1114016700100050005', 'level4A': '명동', 'level4AC': '1114055000', 'level5': '5-5', 'detail': '시청광장지하쇼핑센터'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.97697862382535', 'y': '37.56569908690188'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '24(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 종로구 종로1가 54 종각역(1호선)'}, 'refined': {'text': '서울특별시 종로구 종로1가 54', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '종로구', 'level3': '', 'level4L': '종로1가', 'level4LC': '1111012600100540000', 'level4A': '종로1.2.3.4가동', 'level4AC': '1111061500', 'level5': '54', 'detail': '종각지하철역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.98199830931809', 'y': '37.57022447270949'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 종로구 종로3가 10-5 종로3가역(1호선)'}, 'refined': {'text': '서울특별시 종로구 종로3가 10-5', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '종로구', 'level3': '', 'level4L': '종로3가', 'level4LC': '1111015600100100005', 'level4A': '종로1.2.3.4가동', 'level4AC': '1111061500', 'level5': '10-5', 'detail': '1호선 종로3가역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.99111734324396', 'y': '37.57051691866718'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '172(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 종로구 종로5가 82-1 종로5가역(1호선)'}, 'refined': {'text': '서울특별시 종로구 종로5가 82-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '종로구', 'level3': '', 'level4L': '종로5가', 'level4LC': '1111016300100820001', 'level4A': '종로5.6가동', 'level4AC': '1111063000', 'level5': '82-1', 'detail': '1호선 종로5가역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.00169910366651', 'y': '37.57112301607899'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '20(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 종로구 창신동 492-1 동대문역(1호선)'}, 'refined': {'text': '서울특별시 종로구 창신동 492-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '종로구', 'level3': '', 'level4L': '창신동', 'level4LC': '1111017400104920001', 'level4A': '창신제2동', 'level4AC': '1111068000', 'level5': '492-1', 'detail': '1호선 동대문역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.01124015955442', 'y': '37.57178268570766'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '21(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 동대문구 신설동 76-5 신설동역(1호선)'}, 'refined': {'text': '서울특별시 동대문구 신설동 76-5', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '동대문구', 'level3': '', 'level4L': '신설동', 'level4LC': '1123010100100760005', 'level4A': '신설동', 'level4AC': '1123051500', 'level5': '76-5', 'detail': '신설동역 1-2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.02596646535295', 'y': '37.576458754585715'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '21(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 동대문구 제기동 65 제기동역(1호선)'}, 'refined': {'text': '서울특별시 동대문구 제기동 65', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '동대문구', 'level3': '', 'level4L': '제기동', 'level4LC': '1123010300100650000', 'level4A': '제기동', 'level4AC': '1123054500', 'level5': '65', 'detail': '제기동역 1호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.04073554717593', 'y': '37.57884778505583'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '24(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 동대문구 전농동 620-69 청량리역(1호선)'}, 'refined': {'text': '서울특별시 동대문구 전농동 620-69', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '동대문구', 'level3': '', 'level4L': '전농동', 'level4LC': '1123010400106200069', 'level4A': '전농제1동', 'level4AC': '1123056000', 'level5': '620-69', 'detail': '청량리역 롯데캐슬 Sky-L65 A동'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.0459491452024', 'y': '37.57981456093725'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '18(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 종로구 숭인동 117 동묘앞역(1호선)'}, 'refined': {'text': '서울특별시 종로구 숭인동 117', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '종로구', 'level3': '', 'level4L': '숭인동', 'level4LC': '1111017500101170000', 'level4A': '숭인제1동', 'level4AC': '1111070000', 'level5': '117', 'detail': '동묘앞역 1호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.01714657067426', 'y': '37.57359173882301'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '20(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 서소문동 90-1 시청역(2호선)'}, 'refined': {'text': '서울특별시 중구 서소문동 90-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '서소문동', 'level4LC': '1114016600100900001', 'level4A': '소공동', 'level4AC': '1114052000', 'level5': '90-1', 'detail': '2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.97551892135382', 'y': '37.5635628727694'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '21(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 을지로1가 100-1 을지로입구역(2호선)'}, 'refined': {'text': '서울특별시 중구 을지로1가 100-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '을지로1가', 'level4LC': '1114010400101000001', 'level4A': '명동', 'level4AC': '1114055000', 'level5': '100-1', 'detail': '2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.98203655020706', 'y': '37.566049006795595'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '20(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 을지로3가 347-3 을지로3가역(2호선)'}, 'refined': {'text': '서울특별시 중구 을지로3가 347-3', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '을지로3가', 'level4LC': '1114015500103470003', 'level4A': '을지로동', 'level4AC': '1114060500', 'level5': '347-3', 'detail': '2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.99022564320325', 'y': '37.56621019286939'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '23(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 을지로4가 267-1 을지로4가역(2호선)'}, 'refined': {'text': '서울특별시 중구 을지로4가 267-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '을지로4가', 'level4LC': '1114015000102670001', 'level4A': '을지로동', 'level4AC': '1114060500', 'level5': '267-1', 'detail': '을지로3구역지하쇼핑'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.99654329367644', 'y': '37.56652833822377'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 을지로 7가 112-3 동대문역사문화공원역(2호선)'}, 'refined': {'text': '서울특별시 중구 을지로7가 7-2', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '을지로7가', 'level4LC': '1114014900100070002', 'level4A': '광희동', 'level4AC': '1114059000', 'level5': '7-2', 'detail': '2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.0091431763642', 'y': '37.565720149477436'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '19(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 중구 신당동 99 신당역(2호선)'}, 'refined': {'text': '서울특별시 중구 신당동 99', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '중구', 'level3': '', 'level4L': '신당동', 'level4LC': '1114016200100990000', 'level4A': '황학동', 'level4AC': '1114067000', 'level5': '99', 'detail': '2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.01666489338176', 'y': '37.56532457661295'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '23(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 성동구 하왕십리동 946-14 상왕십리역(2호선)'}, 'refined': {'text': '서울특별시 성동구 하왕십리동 946-14', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '성동구', 'level3': '', 'level4L': '하왕십리동', 'level4LC': '1120010200109460014', 'level4A': '왕십리제2동', 'level4AC': '1120052000', 'level5': '946-14', 'detail': '지하철 2호선'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.02979849026428', 'y': '37.56395875706231'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '17(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 성동구 행당동 192 왕십리역(2호선)'}, 'refined': {'text': '서울특별시 성동구 행당동 192-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '성동구', 'level3': '', 'level4L': '행당동', 'level4LC': '1120010700101920001', 'level4A': '', 'level4AC': '', 'level5': '192-1', 'detail': ''}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.03714332055517', 'y': '37.562613763158836'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '25(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 성동구 행당동 산17 한양대역(2호선)'}, 'refined': {'text': '서울특별시 성동구 행당동 17', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '성동구', 'level3': '', 'level4L': '행당동', 'level4LC': '1120010700100170000', 'level4A': '사근동', 'level4AC': '1120055000', 'level5': '17', 'detail': '한양대학교'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.0424897521126', 'y': '37.558425517748546'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '23(ms)'}, 'status': 'NOT_FOUND', 'record': {'total': '0', 'current': '0'}, 'page': {'total': '1', 'current': '1', 'size': '10'}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 성동구 성수동2가 300-1 성수역(2호선)'}, 'refined': {'text': '서울특별시 성동구 성수동2가 300-1', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '성동구', 'level3': '', 'level4L': '성수동2가', 'level4LC': '1120011500103000001', 'level4A': '성수2가제3동', 'level4AC': '1120069000', 'level5': '300-1', 'detail': ''}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.05697499996353', 'y': '37.5446676579983'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '20(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 광진구 화양동 7-3 2호선 건대입구역(2호선)'}, 'refined': {'text': '서울특별시 광진구 화양동 7-3', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '광진구', 'level3': '', 'level4L': '화양동', 'level4LC': '1121510700100070003', 'level4A': '화양동', 'level4AC': '1121571000', 'level5': '7-3', 'detail': '한림타워'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.06900569903979', 'y': '37.540810120399165'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '26(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 광진구 구의동 245-24 구의역(2호선)'}, 'refined': {'text': '서울특별시 광진구 구의동 245-24', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '광진구', 'level3': '', 'level4L': '구의동', 'level4LC': '1121510300102450024', 'level4A': '자양제2동', 'level4AC': '1121583000', 'level5': '245-24', 'detail': ''}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.09076569612053', 'y': '37.53832091995129'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '20(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 광진구 구의동 546-6 강변역(2호선)'}, 'refined': {'text': '서울특별시 광진구 구의동 546-6', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '광진구', 'level3': '', 'level4L': '구의동', 'level4LC': '1121510300105460006', 'level4A': '구의제3동', 'level4AC': '1121587000', 'level5': '546-6', 'detail': ''}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.0945513653893', 'y': '37.53536788529187'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '21(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 송파구 신천동 15 잠실나루역(2호선)'}, 'refined': {'text': '서울특별시 송파구 신천동 15', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '송파구', 'level3': '', 'level4L': '신천동', 'level4LC': '1171010200100150000', 'level4A': '잠실6동', 'level4AC': '1171071000', 'level5': '15', 'detail': '잠실나루역 역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.10489876358551', 'y': '37.51860475458906'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '17(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 송파구 신천동 8 잠실역(2호선)'}, 'refined': {'text': '서울특별시 송파구 신천동 8', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '송파구', 'level3': '', 'level4L': '신천동', 'level4LC': '1171010200100080000', 'level4A': '잠실6동', 'level4AC': '1171071000', 'level5': '8', 'detail': '잠실역(2호선) 지하철역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.10213953457507', 'y': '37.514055707469424'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '19(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 송파구 잠실동 33 잠실새내역(2호선)'}, 'refined': {'text': '서울특별시 송파구 잠실동 33', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '송파구', 'level3': '', 'level4L': '잠실동', 'level4LC': '1171010100100330000', 'level4A': '잠실2동', 'level4AC': '1171067000', 'level5': '33', 'detail': ''}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.09053465298614', 'y': '37.5115977360373'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '17(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 송파구 잠실동 122 종합운동장역(2호선)'}, 'refined': {'text': '서울특별시 송파구 잠실동 122', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '송파구', 'level3': '', 'level4L': '잠실동', 'level4LC': '1171010100101220000', 'level4A': '잠실7동', 'level4AC': '1171072000', 'level5': '122', 'detail': '지하철 역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.07431642424432', 'y': '37.51111104682337'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 강남구 삼성동 172-66 삼성역(2호선)'}, 'refined': {'text': '서울특별시 강남구 삼성동 172-66', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '강남구', 'level3': '', 'level4L': '삼성동', 'level4LC': '1168010500101720066', 'level4A': '삼성2동', 'level4AC': '1168059000', 'level5': '172-66', 'detail': '선릉역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.05804519956439', 'y': '37.50741516222575'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '26(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 강남구 삼성동 172-66 선릉역(2호선)'}, 'refined': {'text': '서울특별시 강남구 삼성동 172-66', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '강남구', 'level3': '', 'level4L': '삼성동', 'level4LC': '1168010500101720066', 'level4A': '삼성2동', 'level4AC': '1168059000', 'level5': '172-66', 'detail': '선릉역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.05804519956439', 'y': '37.50741516222575'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 강남구 역삼동 804 역삼역(2호선)'}, 'refined': {'text': '서울특별시 강남구 역삼동 804', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '강남구', 'level3': '', 'level4L': '역삼동', 'level4LC': '1168010100108040000', 'level4A': '역삼1동', 'level4AC': '1168064000', 'level5': '804', 'detail': '강남역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.03826825217584', 'y': '37.50124661553012'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '20(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 강남구 역삼동 858 강남역(2호선)'}, 'refined': {'text': '서울특별시 강남구 역삼동 858', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '강남구', 'level3': '', 'level4L': '역삼동', 'level4LC': '1168010100108580000', 'level4A': '역삼1동', 'level4AC': '1168064000', 'level5': '858', 'detail': '강남역'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.02825466705154', 'y': '37.49690083197402'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '21(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 서초구 서초동 1748-4 교대역(2호선)'}, 'refined': {'text': '서울특별시 서초구 서초동 1748-4', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '서초구', 'level3': '', 'level4L': '서초동', 'level4LC': '1165010800117480004', 'level4A': '서초1동', 'level4AC': '1165051000', 'level5': '1748-4', 'detail': '2,3호선철도역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.01732110864319', 'y': '37.494869355779116'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '23(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 서초구 서초동 1748-5 서초역(2호선)'}, 'refined': {'text': '서울특별시 서초구 서초동 1748-5', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '서초구', 'level3': '', 'level4L': '서초동', 'level4LC': '1165010800117480005', 'level4A': '서초3동', 'level4AC': '1165053000', 'level5': '1748-5', 'detail': '2호선철도역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '127.01056934732614', 'y': '37.492795048568965'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '26(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 서초구 방배동 912-14 방배역(2호선)'}, 'refined': {'text': '서울특별시 서초구 방배동 912-14', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '서초구', 'level3': '', 'level4L': '방배동', 'level4LC': '1165010100109120014', 'level4A': '방배3동', 'level4AC': '1165062000', 'level5': '912-14', 'detail': '2호선철도역사'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.99734057563953', 'y': '37.481340458496646'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '18(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 동작구 사당동 1129 사당역(2호선)'}, 'refined': {'text': '서울특별시 동작구 사당동 1129', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'level2': '동작구', 'level3': '', 'level4L': '사당동', 'level4LC': '1159010700111290000', 'level4A': '남현동', 'level4AC': '1162063000', 'level5': '1129', 'detail': '사당역(2호선)'}}, 'result': {'crs': 'EPSG:4326', 'point': {'x': '126.97338828084669', 'y': '37.47611362661153'}}}}, {'response': {'service': {'name': 'address', 'version': '2.0', 'operation': 'getcoord', 'time': '22(ms)'}, 'status': 'OK', 'input': {'type': 'parcel', 'address': '서울특별시 관악구 봉천동 1693-39 낙성대역(2호선)'}, 'refined': {'text': '서울특별시 관악구 봉천동 1693-39', 'structure': {'level0': '대한민국', 'level1': '서울특별시', 'le

### STEP 3. 데이터 전처리
- 전처리 0) status 가 ok 인 경우에 대해서만 처리한다
  
- 전처리 1) geo_result_dict_list 리스트를 탐색해서 안에 있는 딕셔너리에 접근

- 전처리 2) 필요한 데이터만 따로 데이터 프레임 형태로 만들어내기 > 리스트 안에 딕셔너리들이 원소로 들어있어야 함
비워져 있는 리스트(result_list)를 준비하고, {address: 주소 , x: x좌표,y:좌표} 형태의 원소들을 append 해주자

In [9]:
result_list =[]
for y,item in enumerate(geo_result_dict_list):

  # staus 가 OK 인 경우에 대해서만 처리한다
  if item['response']['status'] =="OK":
    
    a= item['response']['input'] 
    b=item['response']['result']

    # 데이터 확인용 : print(y+1, a['address'], "의", "x의 좌표는", b['point']['x'] ,",y의 좌표는", b['point']['y'] )
    dict ={"OLD_ADDR":a['address'],"longitude":b['point']['x'],"latitude":b['point']['y'] }
    result_list.append(dict)


print(result_list)

[{'OLD_ADDR': '서울특별시 중구 남대문로5가 73-6 서울역(1호선)', 'longitude': '126.97254323694754', 'latitude': '37.55702928798156'}, {'OLD_ADDR': '서울특별시 중구 정동 5-5 시청역(1호선)', 'longitude': '126.97697862382535', 'latitude': '37.56569908690188'}, {'OLD_ADDR': '서울특별시 종로구 종로1가 54 종각역(1호선)', 'longitude': '126.98199830931809', 'latitude': '37.57022447270949'}, {'OLD_ADDR': '서울특별시 종로구 종로3가 10-5 종로3가역(1호선)', 'longitude': '126.99111734324396', 'latitude': '37.57051691866718'}, {'OLD_ADDR': '서울특별시 종로구 종로5가 82-1 종로5가역(1호선)', 'longitude': '127.00169910366651', 'latitude': '37.57112301607899'}, {'OLD_ADDR': '서울특별시 종로구 창신동 492-1 동대문역(1호선)', 'longitude': '127.01124015955442', 'latitude': '37.57178268570766'}, {'OLD_ADDR': '서울특별시 동대문구 신설동 76-5 신설동역(1호선)', 'longitude': '127.02596646535295', 'latitude': '37.576458754585715'}, {'OLD_ADDR': '서울특별시 동대문구 제기동 65 제기동역(1호선)', 'longitude': '127.04073554717593', 'latitude': '37.57884778505583'}, {'OLD_ADDR': '서울특별시 동대문구 전농동 620-69 청량리역(1호선)', 'longitude': '127.0459491452024', 'latitude': '37.57981456093725'}, {'OLD_ADDR': '서울특별시 종로구 숭인동 117 동묘앞역(1호선)', 'longitude': '127.01714657067426', 'latitude': '37.57359173882301'}, {'OLD_ADDR': '서울특별시 중구 서소문동 90-1 시청역(2호선)', 'longitude': '126.97551892135382', 'latitude': '37.5635628727694'}, {'OLD_ADDR': '서울특별시 중구 을지로1가 100-1 을지로입구역(2호선)', 'longitude': '126.98203655020706', 'latitude': '37.566049006795595'}, {'OLD_ADDR': '서울특별시 중구 을지로3가 347-3 을지로3가역(2호선)', 'longitude': '126.99022564320325', 'latitude': '37.56621019286939'}, {'OLD_ADDR': '서울특별시 중구 을지로4가 267-1 을지로4가역(2호선)', 'longitude': '126.99654329367644', 'latitude': '37.56652833822377'}, {'OLD_ADDR': '서울특별시 중구 을지로 7가 112-3 동대문역사문화공원역(2호선)', 'longitude': '127.0091431763642', 'latitude': '37.565720149477436'}, {'OLD_ADDR': '서울특별시 중구 신당동 99 신당역(2호선)', 'longitude': '127.01666489338176', 'latitude': '37.56532457661295'}, {'OLD_ADDR': '서울특별시 성동구 하왕십리동 946-14 상왕십리역(2호선)', 'longitude': '127.02979849026428', 'latitude': '37.56395875706231'}, {'OLD_ADDR': '서울특별시 성동구 행당동 192 왕십리역(2호선)', 'longitude': '127.03714332055517', 'latitude': '37.562613763158836'}, {'OLD_ADDR': '서울특별시 성동구 행당동 산17 한양대역(2호선)', 'longitude': '127.0424897521126', 'latitude': '37.558425517748546'}, {'OLD_ADDR': '서울특별시 성동구 성수동2가 300-1 성수역(2호선)', 'longitude': '127.05697499996353', 'latitude': '37.5446676579983'}, {'OLD_ADDR': '서울특별시 광진구 화양동 7-3 2호선 건대입구역(2호선)', 'longitude': '127.06900569903979', 'latitude': '37.540810120399165'}, {'OLD_ADDR': '서울특별시 광진구 구의동 245-24 구의역(2호선)', 'longitude': '127.09076569612053', 'latitude': '37.53832091995129'}, {'OLD_ADDR': '서울특별시 광진구 구의동 546-6 강변역(2호선)', 'longitude': '127.0945513653893', 'latitude': '37.53536788529187'}, {'OLD_ADDR': '서울특별시 송파구 신천동 15 잠실나루역(2호선)', 'longitude': '127.10489876358551', 'latitude': '37.51860475458906'}, {'OLD_ADDR': '서울특별시 송파구 신천동 8 잠실역(2호선)', 'longitude': '127.10213953457507', 'latitude': '37.514055707469424'}, {'OLD_ADDR': '서울특별시 송파구 잠실동 33 잠실새내역(2호선)', 'longitude': '127.09053465298614', 'latitude': '37.5115977360373'}, {'OLD_ADDR': '서울특별시 송파구 잠실동 122 종합운동장역(2호선)', 'longitude': '127.07431642424432', 'latitude': '37.51111104682337'}, {'OLD_ADDR': '서울특별시 강남구 삼성동 172-66 삼성역(2호선)', 'longitude': '127.05804519956439', 'latitude': '37.50741516222575'}, {'OLD_ADDR': '서울특별시 강남구 삼성동 172-66 선릉역(2호선)', 'longitude': '127.05804519956439', 'latitude': '37.50741516222575'}, {'OLD_ADDR': '서울특별시 강남구 역삼동 804 역삼역(2호선)', 'longitude': '127.03826825217584', 'latitude': '37.50124661553012'}, {'OLD_ADDR': '서울특별시 강남구 역삼동 858 강남역(2호선)', 'longitude': '127.02825466705154', 'latitude': '37.49690083197402'}, {'OLD_ADDR': '서울특별시 서초구 서초동 1748-4 교대역(2호선)', 'longitude': '127.01732110864319', 'latitude': '37.494869355779116'}, {'OLD_ADDR': '서울특별시 서초구 서초동 1748-5 서초역(2호선)', 'longitude': '127.01056934732614', 'latitude': '37.492795048568965'}, {'OLD_ADDR': '서울특별시 서초구 방배동 912-14 방배역(2호선)', 'longitude': '126.99734057563953', 'latitude': '37.481340458496646'}, {'OLD_ADDR': '서울특별시 동작구 사당동 1129 사당역(2호선)', 'longitude': '126.97338828084669', 'latitude': '37.47611362661153'}, {'OLD_ADDR': '서울특별시 관악구 봉천동 1693-39 낙성대역(2호선)', 'longitude': '126.96461024920026', 'latitude': '37.47666206007821'}, {'OLD_ADDR': '서울특별시 관악구 봉천동 979-2 서울대입구역(2호선)', 'longitude': '126.95259553211233', 'latitude': '37.480922797330024'}, {'OLD_ADDR': '서울특별시 관악구 신림동 1467-10 신림역(2호선)', 'longitude': '126.92964508188507', 'latitude': '37.484659268305165'}, {'OLD_ADDR': '서울특별시 동작구 신대방동 643-1 신대방역(2호선)', 'longitude': '126.91287649097016', 'latitude': '37.48750928777851'}, {'OLD_ADDR': '서울특별시 구로구 구로동 810-3 구로디지털단지역(2호선)', 'longitude': '126.9008626048798', 'latitude': '37.48544601545602'}, {'OLD_ADDR': '서울특별시 구로구 구로동 1204 대림역(2호선)', 'longitude': '126.89480007937897', 'latitude': '37.49336321842789'}, {'OLD_ADDR': '서울특별시 구로구 신도림동 460-26 신도림역(2호선)', 'longitude': '126.89107234320724', 'latitude': '37.508723230890546'}, {'OLD_ADDR': '서울특별시 영등포구 문래동3가 68-1 문래역(2호선)', 'longitude': '126.894728286571', 'latitude': '37.5178620328131'}, {'OLD_ADDR': '서울특별시 영등포구 당산동3가 270-1 영등포구청역(2호선)', 'longitude': '126.89651107576128', 'latitude': '37.52534872675051'}, {'OLD_ADDR': '서울특별시 영등포구 당산동 6가 323-1 당산역(2호선)', 'longitude': '126.90614394405928', 'latitude': '37.53255283863791'}, {'OLD_ADDR': '서울특별시 마포구 서교동 393 합정역(2호선)', 'longitude': '126.9151830497851', 'latitude': '37.551029103629716'}, {'OLD_ADDR': '서울특별시 마포구 동교동 165 홍대입구역(2호선)', 'longitude': '126.92415848619729', 'latitude': '37.55675374373833'}, {'OLD_ADDR': '서울특별시 마포구 노고산동 31-11 신촌역(2호선)', 'longitude': '126.93750975017635', 'latitude': '37.55468232763202'}, {'OLD_ADDR': '서울특별시 마포구 염리동 8-85 이대역(2호선)', 'longitude': '126.94778839962228', 'latitude': '37.55685481012151'}, {'OLD_ADDR': '서울특별시 마포구 아현동 354-23 아현역(2호선)', 'longitude': '126.95567165564654', 'latitude': '37.555937236104'}, {'OLD_ADDR': '서울특별시 서대문구 충정로3가 319-1 충정로역(2호선)', 'longitude': '126.96385039699553', 'latitude': '37.5595361388535'}, {'OLD_ADDR': '서울특별시 성동구 용답동 127 용답역(2호선)', 'longitude': '127.05445516828708', 'latitude': '37.565436455516405'}, {'OLD_ADDR': '서울특별시 성동구 용답동 129-2 신답역(2호선)', 'longitude': '127.04591835365173', 'latitude': '37.570561292001166'}, {'OLD_ADDR': '서울특별시 동대문구 신설동 76-5 신설동역(2호선)', 'longitude': '127.02596646535295', 'latitude': '37.576458754585715'}, {'OLD_ADDR': '서울특별시 구로구 신도림동 323-16 도림천역(2호선)', 'longitude': '126.88295084907824', 'latitude': '37.514290417674935'}, {'OLD_ADDR': '서울특별시 양천구 신정동 276-7 양천구청역(2호선)', 'longitude': '126.86572204469863', 'latitude': '37.51255816129711'}, {'OLD_ADDR': '서울특별시 양천구 신정동 1231 신정네거리역(2호선)', 'longitude': '126.85362828555401', 'latitude': '37.51833134731362'}, {'OLD_ADDR': '서울특별시 동대문구 용두동 47-1 용두역(2호선)', 'longitude': '127.03819390642585', 'latitude': '37.57596645849121'}, {'OLD_ADDR': '경기도 고양시 덕양구 지축동 818-64 지축역(3호선)', 'longitude': '126.91083271312485', 'latitude': '37.64884663441474'}, {'OLD_ADDR': '서울특별시 은평구 진관동 67-26 구파발역(3호선)', 'longitude': '126.91881198956952', 'latitude': '37.637150819361246'}, {'OLD_ADDR': '서울특별시 은평구 갈현동 397 연신내역(3호선)', 'longitude': '126.92088141647224', 'latitude': '37.61900148871485'}, {'OLD_ADDR': '서울특별시 은평구 대조동 13-10 불광역(3호선)', 'longitude': '126.92986668889455', 'latitude': '37.61039440840224'}, {'OLD_ADDR': '서울특별시 은평구 녹번동 55 녹번역(3호선)', 'longitude': '126.9359828053225', 'latitude': '37.60087917563577'}, {'OLD_ADDR': '서울특별시 서대문구 홍제동 161-1 홍제역(3호선)', 'longitude': '126.94584268614528', 'latitude': '37.58731668135229'}, {'OLD_ADDR': '서울특별시 서대문구 홍제동 26-1 무악재역(3호선)', 'longitude': '126.9505757623475', 'latitude': '37.58241916216521'}, {'OLD_ADDR': '서울특별시 서대문구 현저동 101 독립문역(3호선)', 'longitude': '126.95603980867767', 'latitude': '37.574481164230804'}, {'OLD_ADDR': '서울특별시 종로구 적선동 81-1 경복궁역(3호선)', 'longitude': '126.97320483919052', 'latitude': '37.57576206727056'}, {'OLD_ADDR': '서울특별시 종로구 안국동 73-1 안국역(3호선)', 'longitude': '126.98508959164447', 'latitude': '37.57702260125815'}, {'OLD_ADDR': '서울특별시 종로구 묘동 20-5 종로3가역(3호선)', 'longitude': '126.99190170663617', 'latitude': '37.571450698745714'}, {'OLD_ADDR': '서울특별시 중구 을지로3가 282-8 을지로3가역(3호선)', 'longitude': '126.9936822607441', 'latitude': '37.56640240930581'}, {'OLD_ADDR': '서울특별시 중구 필동2가 16-2 충무로역(3호선)', 'longitude': '126.9944755023148', 'latitude': '37.56120906404675'}, {'OLD_ADDR': '서울특별시 중구 장충동2가 199-3 동대입구역(3호선)', 'longitude': '127.00529745806693', 'latitude': '37.55925834356843'}, {'OLD_ADDR': '서울특별시 중구 신당동 369-44 약수역(3호선)', 'longitude': '127.01091834279731', 'latitude': '37.554439745474085'}, {'OLD_ADDR': '서울특별시 성동구 금호동4가 1470 금호역(3호선)', 'longitude': '127.01577026479131', 'latitude': '37.548165660159896'}, {'OLD_ADDR': '서울특별시 성동구 옥수동 168-1 옥수역(3호선)', 'longitude': '127.01722404470951', 'latitude': '37.539920078540305'}, {'OLD_ADDR': '서울특별시 강남구 신사동 668 압구정역(3호선)', 'longitude': '127.02830752058232', 'latitude': '37.52356009931247'}, {'OLD_ADDR': '서울특별시 강남구 신사동 667 신사역(3호선)', 'longitude': '127.01881616709886', 'latitude': '37.51897154781347'}, {'OLD_ADDR': '서울특별시 서초구 잠원동 100-1 잠원역(3호선)', 'longitude': '127.01174548067499', 'latitude': '37.51306289209155'}, {'OLD_ADDR': '서울특별시 서초구 반포동 19-11 고속터미널역(3호선)', 'longitude': '127.00475326349047', 'latitude': '37.505182733224444'}, {'OLD_ADDR': '서울특별시 서초구 서초동 1748-4 교대역(3호선)', 'longitude': '127.01732110864319', 'latitude': '37.494869355779116'}, {'OLD_ADDR': '서울특별시 서초구 서초동 1748-30 남부터미널역(3호선)', 'longitude': '127.015296902816', 'latitude': '37.486594550622534'}, {'OLD_ADDR': '서울특별시 서초구 서초동 1366-9 양재역(3호선)', 'longitude': '127.03327100796304', 'latitude': '37.48478871255944'}, {'OLD_ADDR': '서울특별시 강남구 도곡동 179-2 매봉역(3호선)', 'longitude': '127.0466459440014', 'latitude': '37.48698731740029'}, {'OLD_ADDR': '서울특별시 강남구 도곡동 339-2 도곡역(3호선)', 'longitude': '127.05499150159866', 'latitude': '37.49071368174434'}, {'OLD_ADDR': '서울특별시 강남구 대치동 317-3 대치역(3호선)', 'longitude': '127.0632469772417', 'latitude': '37.49451867591994'}, {'OLD_ADDR': '서울특별시 강남구 대치동 514-3 학여울역(3호선)', 'longitude': '127.07179754200895', 'latitude': '37.49672331116055'}, {'OLD_ADDR': '서울특별시 강남구 일원동 700-9 대청역(3호선)', 'longitude': '127.07958695946226', 'latitude': '37.493670961743575'}, {'OLD_ADDR': '서울특별시 강남구 일원동 717 일원역(3호선)', 'longitude': '127.08443881200125', 'latitude': '37.48405310920885'}, {'OLD_ADDR': '서울특별시 강남구 수서동 728 수서역(3호선)', 'longitude': '127.10040668861537', 'latitude': '37.488352701415536'}, {'OLD_ADDR': '서울특별시 송파구 가락동 184-23 가락시장역(3호선)', 'longitude': '127.11823739050217', 'latitude': '37.49291656037441'}, {'OLD_ADDR': '서울특별시 송파구 가락동 10-15 경찰병원역(3호선)', 'longitude': '127.12570434843565', 'latitude': '37.498357750136385'}, {'OLD_ADDR': '서울특별시 송파구 오금동 44-2 오금역(3호선)', 'longitude': '127.1263953175756', 'latitude': '37.503258874591374'}, {'OLD_ADDR': '서울특별시 노원구 상계동 111 당고개역(4호선)', 'longitude': '127.08233104705232', 'latitude': '37.671230453856055'}, {'OLD_ADDR': '서울특별시 노원구 상계동 156-203 상계역(4호선)', 'longitude': '127.0737420937495', 'latitude': '37.66116246599688'}, {'OLD_ADDR': '서울특별시 노원구 상계동 602-5 노원역(4호선)', 'longitude': '127.06232914605272', 'latitude': '37.65608735761785'}, {'OLD_ADDR': '서울특별시 도봉구 창동 135-1 창동역(4호선)', 'longitude': '127.0475407528857', 'latitude': '37.653668999367824'}, {'OLD_ADDR': '서울특별시 도봉구 창동 703-4 쌍문역(4호선)', 'longitude': '127.03502803420179', 'latitude': '37.64897421818273'}, {'OLD_ADDR': '서울특별시 강북구 수유동 140 수유역(4호선)', 'longitude': '127.02722259341354', 'latitude': '37.639822439425885'}, {'OLD_ADDR': '서울특별시 강북구 미아동 194-1 미아역(4호선)', 'longitude': '127.02472070228688', 'latitude': '37.62994132897778'}, {'OLD_ADDR': '서울특별시 강북구 미아동 66-1 미아사거리역(4호선)', 'longitude': '127.03002733569922', 'latitude': '37.61512809460614'}, {'OLD_ADDR': '서울특별시 성북구 동선동4가 1 성신여대입구역(4호선)', 'longitude': '127.01679743961165', 'latitude': '37.593102120459776'}, {'OLD_ADDR': '서울특별시 성북구 삼선동1가 14 한성대입구역(4호선)', 'longitude': '127.00581011495694', 'latitude': '37.58807415462359'}, {'OLD_ADDR': '서울특별시 종로구 명륜4가 96-5 혜화역(4호선)', 'longitude': '127.00177686245729', 'latitude': '37.58219181865668'}, {'OLD_ADDR': '서울특별시 종로구 종로6가 287-1 동대문역(4호선)', 'longitude': '127.00951644803524', 'latitude': '37.57057353798165'}, {'OLD_ADDR': '서울특별시 중구 광희동2가 9 동대문역사문화공원역(4호선)', 'longitude': '127.0072567744177', 'latitude': '37.56451439822429'}, {'OLD_ADDR': '서울특별시 중구 필동2가 16-2 충무로역(4호선)', 'longitude': '126.9944755023148', 'latitude': '37.56120906404675'}, {'OLD_ADDR': '서울특별시 중구 충무로2가 109-2 명동역(4호선)', 'longitude': '126.98573268089424', 'latitude': '37.56085122284385'}, {'OLD_ADDR': '서울특별시 중구 남창동 64-1 회현역(4호선)', 'longitude': '126.97726579723081', 'latitude': '37.5590649207668'}, {'OLD_ADDR': '서울특별시 용산구 동자동 14-151 서울역 (4호선)', 'longitude': '126.97280175236627', 'latitude': '37.5531212223581'}, {'OLD_ADDR': '서울특별시 용산구 갈월동 16-7 숙대입구역(4호선)', 'longitude': '126.97193304702314', 'latitude': '37.545584369637226'}, {'OLD_ADDR': '서울특별시 용산구 한강로1가 228-1 삼각지역(4호선)', 'longitude': '126.97306304108558', 'latitude': '37.53443527493232'}, {'OLD_ADDR': '서울특별시 용산구 한강로2가 181 신용산역(4호선)', 'longitude': '126.96802942474334', 'latitude': '37.529237996972206'}, {'OLD_ADDR': '서울특별시 용산구 용산동5가 17-112 이촌역(4호선)', 'longitude': '126.97529872462472', 'latitude': '37.521966316931604'}, {'OLD_ADDR': '서울특별시 동작구 동작동 327-1 동작역(4호선)', 'longitude': '126.98003103038873', 'latitude': '37.502794446120994'}, {'OLD_ADDR': '서울특별시 동작구 사당동 736-1 총신대입구(이수)역(4호선)', 'longitude': '126.98227697302903', 'latitude': '37.48816344653054'}, {'OLD_ADDR': '서울특별시 동작구 사당동 588-44 사당역(4호선)', 'longitude': '126.98163128362717', 'latitude': '37.476909774212615'}, {'OLD_ADDR': '서울특별시 서초구 방배동 2909 남태령역(4호선)', 'longitude': '126.98927987255419', 'latitude': '37.464409539066736'}, {'OLD_ADDR': '서울특별시 강서구 방화동 829-15 방화역(5호선)', 'longitude': '126.81266272024443', 'latitude': '37.57727059528708'}, {'OLD_ADDR': '서울특별시 강서구 방화동 846 개화산역(5호선)', 'longitude': '126.80573003779573', 'latitude': '37.57233556637786'}, {'OLD_ADDR': '서울특별시 강서구 방화동 886 김포공항역(5호선)', 'longitude': '126.80295629724978', 'latitude': '37.56680557870223'}, {'OLD_ADDR': '서울특별시 강서구 공항동 29-5 송정역(5호선)', 'longitude': '126.81055344845655', 'latitude': '37.56147269586097'}, {'OLD_ADDR': '서울특별시 강서구 마곡동 769-3 마곡역(5호선)', 'longitude': '126.82481516761638', 'latitude': '37.56030052001876'}, {'OLD_ADDR': '서울특별시 강서구 마곡동 727-1496 발산역(5호선)', 'longitude': '126.83696331789548', 'latitude': '37.55893833925971'}, {'OLD_ADDR': '서울특별시 강서구 화곡동 1089-3 우장산역(5호선)', 'longitude': '126.83641327415941', 'latitude': '37.54892715617271'}, {'OLD_ADDR': '서울특별시 강서구 화곡동 1089-54 화곡역(5호선)', 'longitude': '126.84084596901616', 'latitude': '37.54112157445881'}, {'OLD_ADDR': '서울특별시 강서구 화곡동 662-5 까치산역(5호선)', 'longitude': '126.84622407637504', 'latitude': '37.53258360321953'}, {'OLD_ADDR': '서울특별시 양천구 신정동 1090 신정역(5호선)', 'longitude': '126.85373101667304', 'latitude': '37.52468854839453'}, {'OLD_ADDR': '서울특별시 양천구 목동 926-3 목동역(5호선)', 'longitude': '126.86589343188112', 'latitude': '37.52603246774737'}, {'OLD_ADDR': '서울특별시 양천구 목동 406-30 오목교역(5호선)', 'longitude': '126.87488069512946', 'latitude': '37.52456500701658'}, {'OLD_ADDR': '서울특별시 영등포구 양평동2가 33-79 양평역(5호선)', 'longitude': '126.88609425175002', 'latitude': '37.52521667922339'}, {'OLD_ADDR': '서울특별시 영등포구 당산동3가 556-1 영등포구청역(5호선)', 'longitude': '126.89426583030894', 'latitude': '37.52440787571844'}, {'OLD_ADDR': '서울특별시 영등포구 영등포동5가 62-1 영등포시장역(5호선)', 'longitude': '126.90528967219188', 'latitude': '37.52218322726378'}, {'OLD_ADDR': '서울특별시 영등포구 영등포동1가 35 신길역(5호선)', 'longitude': '126.91459956659163', 'latitude': '37.51772036156411'}, {'OLD_ADDR': '서울특별시 영등포구 여의도동 3 여의도역(5호선)', 'longitude': '126.9265137386989', 'latitude': '37.523094430512316'}, {'OLD_ADDR': '서울특별시 영등포구 여의도동 84-4 여의나루역(5호선)', 'longitude': '126.93229703459717', 'latitude': '37.52826077166671'}, {'OLD_ADDR': '서울특별시 마포구 도화동 160 마포역(5호선)', 'longitude': '126.94485656703787', 'latitude': '37.53867766506842'}, {'OLD_ADDR': '서울특별시 마포구 공덕동 423-29 공덕역(5호선)', 'longitude': '126.95121364689737', 'latitude': '37.5445102809178'}, {'OLD_ADDR': '서울특별시 마포구 아현동 612 애오개역(5호선)', 'longitude': '126.95648075904414', 'latitude': '37.55397366478634'}, {'OLD_ADDR': '서울특별시 서대문구 충정로3가 248-1 충정로역(5호선)', 'longitude': '126.96328984444074', 'latitude': '37.56071431037026'}, {'OLD_ADDR': '서울특별시 종로구 평동 210 서대문역(5호선)', 'longitude': '126.96694531216497', 'latitude': '37.56618064500036'}, {'OLD_ADDR': '서울특별시 종로구 세종로 1-68 5호선 광화문역(5호선)', 'longitude': '126.9769157235392', 'latitude': '37.57249944447308'}, {'OLD_ADDR': '서울특별시 종로구 돈의동 39-1 5호선 종로3가역(5호선)', 'longitude': '126.99034167215973', 'latitude': '37.57255294150529'}, {'OLD_ADDR': '서울특별시 중구 주교동 191 을지로4가역(5호선)', 'longitude': '126.99803206617884', 'latitude': '37.567433312265095'}, {'OLD_ADDR': '서울특별시 중구 광희동1가 235-6 동대문역사문화공원역(5호선)', 'longitude': '127.00623511761606', 'latitude': '37.564605098120495'}, {'OLD_ADDR': '서울특별시 중구 신당동 295-2 청구역(5호선)', 'longitude': '127.0138510701361', 'latitude': '37.560311135351554'}, {'OLD_ADDR': '서울특별시 성동구 금호동2가 223-1 신금호역(5호선)', 'longitude': '127.01993837175019', 'latitude': '37.554948698863384'}, {'OLD_ADDR': '서울특별시 성동구 행당동 192 왕십리역(5호선)', 'longitude': '127.03714332055517', 'latitude': '37.562613763158836'}, {'OLD_ADDR': '서울특별시 성동구 마장동 804 마장역(5호선)', 'longitude': '127.04451808369473', 'latitude': '37.567204799896416'}, {'OLD_ADDR': '서울특별시 성동구 용답동 99 답십리역(5호선)', 'longitude': '127.05229031968503', 'latitude': '37.56689918916539'}, {'OLD_ADDR': '서울특별시 동대문구 장안동 472-3 장한평역(5호선)', 'longitude': '127.05829705576473', 'latitude': '37.56283096720627'}, {'OLD_ADDR': '서울특별시 광진구 능동 275-5 군자(능동)역(5호선)', 'longitude': '127.08080757490575', 'latitude': '37.556623132660306'}, {'OLD_ADDR': '서울특별시 광진구 능동 256-16 5호선 아차산역(5호선)', 'longitude': '127.08716759429262', 'latitude': '37.55404467878992'}, {'OLD_ADDR': '서울특별시 광진구 광장동 237 광나루역(5호선)', 'longitude': '127.10350483065346', 'latitude': '37.54521596350433'}, {'OLD_ADDR': '서울특별시 강동구 천호동 455 천호역(5호선)', 'longitude': '127.12510964987322', 'latitude': '37.53850964433742'}, {'OLD_ADDR': '서울특별시 강동구 천호동 447 강동역(5호선)', 'longitude': '127.1341493959259', 'latitude': '37.535801612759855'}, {'OLD_ADDR': '서울특별시 강동구 길동 378 길동역(5호선)', 'longitude': '127.13970874653009', 'latitude': '37.538610651228666'}, {'OLD_ADDR': '서울특별시 강동구 명일동 345-12 굽은다리역(5호선)', 'longitude': '127.14317766077738', 'latitude': '37.54606880616424'}, {'OLD_ADDR': '서울특별시 강동구 명일동 312 명일역(5호선)', 'longitude': '127.1428914705283', 'latitude': '37.55357089027942'}, {'OLD_ADDR': '서울특별시 강동구 고덕동 310 고덕역(5호선)', 'longitude': '127.15395765431595', 'latitude': '37.555479341651704'}, {'OLD_ADDR': '서울특별시 강동구 상일동 148 상일동역(5호선)', 'longitude': '127.15695552602782', 'latitude': '37.554441753815745'}, {'OLD_ADDR': '서울특별시 송파구 방이동 89-28 올림픽공원역(5호선)', 'longitude': '127.13097514766757', 'latitude': '37.51626838285428'}, {'OLD_ADDR': '서울특별시 송파구 방이동 217-2 방이역(5호선)', 'longitude': '127.12504572928987', 'latitude': '37.50728250100633'}, {'OLD_ADDR': '서울특별시 송파구 오금동 44-2 오금역(5호선)', 'longitude': '127.1263953175756', 'latitude': '37.503258874591374'}, {'OLD_ADDR': '서울특별시 송파구 가락동 165-2 개롱역(5호선)', 'longitude': '127.13306592811344', 'latitude': '37.49893283410732'}, {'OLD_ADDR': '서울특별시 송파구 거여동 20-14 거여역(5호선)', 'longitude': '127.14194980431802', 'latitude': '37.49428691489842'}, {'OLD_ADDR': '서울특별시 송파구 마천동 307-4 마천역(5호선)', 'longitude': '127.15184620409948', 'latitude': '37.49435059226771'}, {'OLD_ADDR': '서울특별시 강동구 상일동 산73 강일역(5호선)', 'longitude': '127.17615876042287', 'latitude': '37.55609507668983'}, {'OLD_ADDR': '경기도 하남시 망월동 1122 미사역(5호선)', 'longitude': '127.1916457838173', 'latitude': '37.56600220390679'}, {'OLD_ADDR': '경기도 하남시 덕풍동 727-3 하남풍산역(5호선)', 'longitude': '127.20478693401063', 'latitude': '37.55328686420194'}, {'OLD_ADDR': '경기도 하남시 덕풍동 405-1 하남시청(덕풍신장)역(5호선)', 'longitude': '127.20621580402101', 'latitude': '37.54185203575889'}, {'OLD_ADDR': '경기도 하남시 창우동 526 하남검단산역(5호선)', 'longitude': '127.22442692107758', 'latitude': '37.53954961408722'}, {'OLD_ADDR': '서울특별시 은평구 신사동 22-15 응암역(6호선)', 'longitude': '126.91544342045918', 'latitude': '37.598077146177516'}, {'OLD_ADDR': '서울특별시 은평구 녹번동 153-31 역촌역(6호선)', 'longitude': '126.9236973783095', 'latitude': '37.605399705314106'}, {'OLD_ADDR': '서울특별시 은평구 대조동 13-10 불광역(6호선)', 'longitude': '126.92986668889455', 'latitude': '37.61039440840224'}, {

### STEP4. 데이터 프레임으로 생성하기
주소지 + X 좌표 + Y 좌표 정보를 데이터 프레임으로 확인
이제 기존 원본 데이터에 주소지를 키값으로 하여 조인 하면 X,Y 좌표를 서울교통공사 데이터와 함께 확인할 수 있게 된다

In [10]:
geo_df = DataFrame(result_list)
geo_df

                            OLD_ADDR           longitude            latitude
0      서울특별시 중구 남대문로5가 73-6 서울역(1호선)  126.97254323694754   37.55702928798156
1           서울특별시 중구 정동 5-5 시청역(1호선)  126.97697862382535   37.56569908690188
2         서울특별시 종로구 종로1가 54 종각역(1호선)  126.98199830931809   37.57022447270949
3     서울특별시 종로구 종로3가 10-5 종로3가역(1호선)  126.99111734324396   37.57051691866718
4     서울특별시 종로구 종로5가 82-1 종로5가역(1호선)  127.00169910366651   37.57112301607899
..                               ...                 ...                 ...
277       서울특별시 송파구 방이동 2 송파나루역(9호선)   127.1127936831653  37.511070749365246
278   서울특별시 송파구 방이동 88-17 한성백제역(9호선)  127.11343167007695  37.518169255351694
279  서울특별시 송파구 방이동 89-28 올림픽공원역(9호선)  127.13097514766757   37.51626838285428
280   서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선)  127.14055711635882  37.518549612102994
281   서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선)  127.14834880144522  37.528334424738375

[282 rows x 3 columns]

### [3] metro_df 와 geo_df 를 pandas 를 활용하여 조인해 하나의 형태로 조합하기

In [12]:
import pandas as pd

merged_df = pd.merge(geo_df, metro_df, on='OLD_ADDR', how='inner')
print(merged_df)

#subway_stations_with_coords 이름으로 저장
merged_df.to_csv("subway_stations_with_coords.csv",index=False,encoding='utf-8')

                            OLD_ADDR           longitude            latitude  \
0      서울특별시 중구 남대문로5가 73-6 서울역(1호선)  126.97254323694754   37.55702928798156
1           서울특별시 중구 정동 5-5 시청역(1호선)  126.97697862382535   37.56569908690188
2         서울특별시 종로구 종로1가 54 종각역(1호선)  126.98199830931809   37.57022447270949
3     서울특별시 종로구 종로3가 10-5 종로3가역(1호선)  126.99111734324396   37.57051691866718
4     서울특별시 종로구 종로5가 82-1 종로5가역(1호선)  127.00169910366651   37.57112301607899
..                               ...                 ...                 ...
277       서울특별시 송파구 방이동 2 송파나루역(9호선)   127.1127936831653  37.511070749365246
278   서울특별시 송파구 방이동 88-17 한성백제역(9호선)  127.11343167007695  37.518169255351694
279  서울특별시 송파구 방이동 89-28 올림픽공원역(9호선)  127.13097514766757   37.51626838285428
280   서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선)  127.14055711635882  37.518549612102994
281   서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선)  127.14834880144522  37.528334424738375

    SBWY_ROUT_LN SBWY_STNS_NM                ROAD_NM_ADDR         TELNO
0            1호선           서울  서울특별시 중구 세종대로 지하2(남대문로 5가)  02-6110-1331
1            1호선           시청     서울특별시 중구 세종대로 지하101(정동)  02-6110-1321
2            1호선           종각     서울특별시 종로구 종로 지하55(종로1가)  02-6110-1311
3            1호선         종로3가    서울특별시 종로구 종로 지하129(종로3가)  02-6110-1301
4            1호선         종로5가    서울특별시 종로구 종로 지하216(종로5가)  02-6110-1291
..           ...          ...                         ...           ...
277          9호선         송파나루  서울특별시 송파구 백제고분로 지하446(방이동)  02-2656-0934
278          9호선         한성백제   서울특별시 송파구 위례성대로 지하29(방이동)  02-2656-0935
279          9호선  올림픽공원(한국체대)  서울특별시 송파구 양재대로 지하1233(방이동)  02-2656-0936
280          9호선         둔촌오륜   서울특별시 강동구 강동대로 지하303(둔촌동)  02-2656-0937
281          9호선       중앙보훈병원    서울특별시 강동구 동남로 지하625(둔촌동)  02-2656-0938

[282 rows x 7 columns]